name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Cloudflared
      run: Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.msi -OutFile cloudflared.msi
    - name: Install Cloudflared
      run: cmd /c "msiexec /i cloudflared.msi /qn"
    - name: Auth and Install Service
      run: |
        $executablePath = "cloudflared"
        $command = "cmd /c `"$executablePath`" service install `"$(${{ secrets.CLOUDFLARE_TOKEN }})`""
        Invoke-Expression $command
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
    - name: Enable TS
      run: cmd /c "reg add \"HKLM\System\CurrentControlSet\Control\Terminal Server\" /v fDenyTSConnections /t REG_DWORD /d 0 /f"
    - name: Enable Firewall Rule
      run: cmd /c "netsh advfirewall firewall set rule group=\"Remote Desktop\" new state=enabled"
    - name: Set User Authentication
      run: cmd /c "reg add \"HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\" /v UserAuthentication /t REG_DWORD /d 1 /f"
    - name: Set Local User Password
      run: cmd /c "net user runneradmin P@ssw0rd! /add && net user runneradmin P@ssw0rd! /domain"
    - name: Configure Tunnel (example, adjust as per your setup)
      run: cmd /c "cloudflared.exe tunnel create --name my-tunnel --url http://localhost:3389"
