name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 下载 Cloudflared
      run: Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.msi -OutFile cloudflared.msi
    - name: 安装 Cloudflared
      run: cmd /c "msiexec /i cloudflared.msi /qn"
    - name: 设置并启动 Cloudflared 服务
      run: '"C:\Program Files\cloudflared\cloudflared.exe" service install $Env:CLOUDFLARE_TOKEN'
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
    - name: 启用 TS
      run: cmd /c "reg add \"HKLM\System\CurrentControlSet\Control\Terminal Server\" /v fDenyTSConnections /t REG_DWORD /d 0 /f"
    - name: 启用远程桌面规则
      run: cmd /c "netsh advfirewall firewall set rule group=\"Remote Desktop\" new state=enabled"
    - name: 设置 TS 规则
      run: cmd /c "reg add \"HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\" /v UserAuthentication /t REG_DWORD /d 1 /f"
    - name: 设置用户密码
      run: cmd /c "net user runneradmin P@ssw0rd! /add && net user runneradmin P@ssw0rd! /domain"
